- name: Varibles from files
  hosts: web
  vars_files: 
  - vars.yaml
  tasks: 
  - name:  Print the course information
   ansible.buitin.debug: 
     msg: "Hi,i'm learning devops {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"
